import type { Chapter } from "@/lib/workbookTypes";

export const chapter10: Chapter = {
  id: "chapter-10",
  chapterNumber: 10,
  title: "Creating My First Prototype",

  sectionTitle: "Building with AI",

  introduction: [
    "This is where your ideas begin to come to life.",
    "A prototype is an early version of your app.",
    "Professional developers create simple versions first, test them, and improve them over time."
  ],

  quote: "Your first version is not your final version.",

  parts: [

    {
      title: "Generating Code with AI",

      background: [
        "AI can help generate computer code.",
        "Think of AI as a coding assistant.",
        "Clear instructions produce better results."
      ],

      quote:
        "The better your instructions, the better the results.",

      leadingQuestions: [
        "What does my app need to do?",
        "Who is using my app?",
        "What features should I include?",
        "How simple can I make Version 1?",
        "Did I clearly explain what I want?"
      ],

      comparisons: [
        {
          weak: "Make an app.",
          better:
            "Create a homework reminder app for middle school students."
        },

        {
          weak:
            "Create a homework reminder app.",
          better:
            "Create a simple homework reminder app using HTML, CSS, and JavaScript. Include large buttons and clear instructions."
        }
      ],

      prompts: [
        {
          type: "textarea",
          id: "promptBuilder",
          label: "Complete the Prompt Builder"
        },

        {
          type: "textarea",
          id: "firstCodingPrompt",
          label: "My First Coding Prompt"
        },

        {
          type: "textarea",
          id: "aiGenerated",
          label: "What did AI generate for you?"
        },

        {
          type: "checkboxGroup",
          id: "prototypeFeatures",
          label: "Features Included in My Prototype",
          options: [
            "Home screen",
            "Buttons",
            "Text",
            "Images",
            "Lists",
            "Input boxes",
            "Save button",
            "Game elements",
            "Score counter"
          ]
        },

        {
          type: "textarea",
          id: "prototypeCode",
          label: "Paste Code Generated by AI"
        }
      ]
    },

    {
      title: "Understanding the Output",

      background: [
        "AI can generate code, but understanding what it creates is still important.",
        "Focus on understanding the big picture rather than every line."
      ],

      bulletPoints: [
        "HTML creates structure.",
        "CSS controls appearance.",
        "JavaScript creates behavior."
      ],

      leadingQuestions: [
        "What does this code do?",
        "Which part creates buttons?",
        "Which part controls colors?",
        "Which part controls actions?",
        "What would happen if I changed something?"
      ],

      examples: [
        {
          language: "HTML",
          purpose: "Creates structure"
        },

        {
          language: "CSS",
          purpose: "Controls appearance"
        },

        {
          language: "JavaScript",
          purpose: "Adds behavior"
        }
      ],

      prompts: [
        {
          type: "textarea",
          id: "recognizeCode",
          label: "Something I recognize in the code"
        },

        {
          type: "textarea",
          id: "dontUnderstandCode",
          label: "Something I do not understand yet"
        },

        {
          type: "textarea",
          id: "questionForAI",
          label: "A question I want to ask AI"
        },

        {
          type: "textarea",
          id: "aiExplanation",
          label: "AI's explanation"
        },

        {
          type: "textarea",
          id: "identifyButton",
          label: "A button I found"
        },

        {
          type: "textarea",
          id: "identifyTitle",
          label: "A title I found"
        },

        {
          type: "textarea",
          id: "identifyColor",
          label: "A color I found"
        },

        {
          type: "textarea",
          id: "identifyAction",
          label: "Something that happens when users click"
        },

        {
          type: "textarea",
          id: "changeCode",
          label: "Something I would like to change"
        }
      ]
    },

    {
      title: "Saving My Work",

      background: [
        "Professional developers save their work frequently.",
        "Saving work allows you to continue improving your app later."
      ],

      quote: "Save early. Save often.",

      leadingQuestions: [
        "Did I save my work today?",
        "Can I find my project later?",
        "Did I use a clear file name?"
      ],

      goodExamples: [
        "HomeworkHelper_v1",
        "PetPalPrototype",
        "MovieTracker_App"
      ],

      poorExamples: [
        "Stuff",
        "Untitled",
        "Final_Final_ReallyFinal",
        "New Project"
      ],

      prompts: [
        {
          type: "text",
          id: "projectName",
          label: "Project Name"
        },

        {
          type: "text",
          id: "fileName",
          label: "File Name"
        },

        {
          type: "textarea",
          id: "projectLocation",
          label: "Where Is My Project Saved?"
        },

        {
          type: "text",
          id: "dateSaved",
          label: "Date Saved"
        },

        {
          type: "textarea",
          id: "version1",
          label: "Version 1: What did I complete?"
        },

        {
          type: "textarea",
          id: "version2",
          label: "Version 2: What did I improve?"
        },

        {
          type: "textarea",
          id: "version3",
          label: "Version 3: What changes did I make?"
        },

        {
          type: "checkboxGroup",
          id: "backupChecklist",
          label: "Backup Checklist",
          options: [
            "I saved my project",
            "I know where my file is located",
            "My file name makes sense",
            "I can open my project again later",
            "I can continue building tomorrow"
          ]
        }
      ]
    },

    {
      title: "My Prototype Summary",

      prompts: [
        {
          type: "text",
          id: "prototypeName",
          label: "My app is called"
        },

        {
          type: "textarea",
          id: "prototypeDoes",
          label: "My prototype currently does"
        },

        {
          type: "textarea",
          id: "prototypeNeeds",
          label: "My prototype still needs"
        },

        {
          type: "textarea",
          id: "proudFeature",
          label: "The feature I am most proud of is"
        },

        {
          type: "imageUpload",
          id: "prototypeScreenshot",
          label: "Upload a Screenshot of Your Prototype"
        },

        {
          type: "url",
          id: "prototypeLink",
          label: "Prototype Link (Optional)"
        }
      ]
    }
  ],

  reflection: [
    {
      id: "prototypeFeeling",
      question:
        "How did it feel to create your first prototype?"
    },

    {
      id: "prototypeSurprise",
      question:
        "What surprised you most?"
    },

    {
      id: "easyCoding",
      question:
        "What part of coding seems easier than you expected?"
    },

    {
      id: "hardCoding",
      question:
        "What part still feels difficult?"
    }
  ],

  nextChapterMessage:
    "In the next chapter, you will learn how to test your app, identify problems, and improve your design through revision and feedback."
};